# -*- coding: utf-8 -*-
"""Project_8_vehicule_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPzVmOFwrGNAocd2U68LYOBkbbAcDTFW

# Vehicule detect count
in this project, we will be working on detecting and counting vehicles in given image or a video. we will be using Opencv for image preprocessing and HAAR Cascade which is used for object detection.
we can also create our own customized haar cascade classifier
"""

# import libraries
import numpy as np
import cv2
from PIL import Image
import requests

# reading image from URl
image = Image.open(requests.get("https://a57.foxnews.com/media.foxbusiness.com/BrightCove/854081161001/201805/2879/931/524/854081161001_5782482890001_5782477388001-vs.jpg", stream =True).raw)
image = image.resize((450, 250))
image_arr = np.array(image)
image

# convert this image to grey for easy processing
grey = cv2.cvtColor(image_arr, cv2.COLOR_BGR2GRAY)
Image.fromarray(grey)

# let's blur the image to take out the noise
blur = cv2.GaussianBlur(grey, (5,5), 0)
Image.fromarray(blur)

# let's dilated the image
dilated = cv2.dilate(blur, np.ones((3,3)))
Image.fromarray(dilated)

# Now let's perform morphology
kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (2,2))
closing = cv2.morphologyEx(dilated, cv2.MORPH_CLOSE, kernel)
Image.fromarray(closing)

# let's use the cascade classifier to indentifier a car
car_cascade_sr = "/content/drive/MyDrive/Vehicule_detect_count/cars.xml"
car_cascade = cv2.CascadeClassifier(car_cascade_sr)
cars = car_cascade.detectMultiScale(closing, 1.1, 1)

# Draw a a reclangle contour around all the card it found
cnt = 0
for (x, y, w, h) in cars:
  cv2.rectangle(image_arr, (x,y), (x+w, y+h), (255,0,0), 2)
  cnt += 1
print(cnt, "cars found")
Image.fromarray(image_arr)

"""## now we will do bus detection

"""

# Reading Image from URL
image2 = Image.open(requests.get('https://qph.fs.quoracdn.net/main-qimg-b5c4e39dcd48dddd9e609e6022f74d85', stream=True).raw)
image2  = image2.resize((450,250))
image2 = np.array(image2)
grey2 = cv2.cvtColor(image2, cv2.COLOR_BGR2GRAY)
Image.fromarray(grey2)

# use the cascade to indentifier a bus
bus_cascade_src = "/content/drive/MyDrive/Vehicule_detect_count/Bus_front.xml"
bus_cascade = cv2.CascadeClassifier(bus_cascade_src)
buses = bus_cascade.detectMultiScale(grey2, 1.1, 1)

# Create rectangle countour around the bus
cnt = 0
for (x, y, w, h) in buses:
  cv2.rectangle(image2, (x,y), (x+w, y+h), (255,0,0), 2)
  cnt += 1
print(cnt, "buses found")
Image.fromarray(image2)

"""### Now let's do a car detection on a video"""

cascade_src = "/content/drive/MyDrive/Vehicule_detect_count/cars.xml"
#video_src = "/content/drive/MyDrive/Vehicule_detect_count/video1.mp4"
video_src = "/content/drive/MyDrive/Vehicule_detect_count/Cars.mp4"
cap = cv2.VideoCapture(video_src)
car_cascade = cv2.CascadeClassifier(cascade_src)
video = cv2.VideoWriter('result.avi',cv2.VideoWriter_fourcc(*'MJPG'),15,(450,250))

while True:
  ret, img = cap.read()
  if (type(img) == type(None)):
    break
  img = cv2.resize(img, (640, 480))
  grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
  cars = car_cascade.detectMultiScale(grey, 1.1, 2)
  for (x, y, w, h) in cars:
    cv2.rectangle(img, (x,y), (x+w, y+h), (255,0,0), 2)
    video.write(img)
  video.release()
  cap.release()

while True:
    ret, img = cap.read()
    if img is None:
        break

    grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    cars = car_cascade.detectMultiScale(grey, 1.1, 2)

    for (x, y, w, h) in cars:
        cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)

    video.write(img)

# ✅ OUTSIDE the loop
video.release()
cap.release()

from IPython.display import Video
Video("result.avi", embed = True)

import os

print("Video exists:", os.path.exists(video_src))
cap = cv2.VideoCapture(video_src)
print("cap opened:", cap.isOpened())

ret, frame = cap.read()
print("first ret:", ret)
print("first frame shape:", None if frame is None else frame.shape)

cap.release()

import cv2

W, H = 450, 250

cap = cv2.VideoCapture(video_src)

# Safer codec than MJPG sometimes in Colab:
# fourcc = cv2.VideoWriter_fourcc(*'XVID')  # try XVID first
# out = cv2.VideoWriter('result.avi', fourcc, 15, (W, H))
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter("result.mp4", fourcc, 15, (W, H))

print("writer opened:", out.isOpened())

frame_count = 0

while True:
    ret, img = cap.read()
    if not ret or img is None:
        break

    img = cv2.resize(img, (W, H))  # ✅ MUST match VideoWriter size

    grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    cars = car_cascade.detectMultiScale(grey, 1.1, 2)

    for (x, y, w, h) in cars:
        cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)

    out.write(img)
    frame_count += 1

out.release()
cap.release()

print("frames written:", frame_count)

from IPython.display import Video
Video("result.mp4", embed=True)

from IPython.display import Video
Video("result.avi", embed=True)

from google.colab import files
files.download("result.avi")

"""### Conclusion
we are at the end of the project .in this project we build a model that can be predict a car or a bus using picture
"""

